-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."BasicHealthUnit"
(
    "CNES" integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default",
    "IBGE_city_code" integer,
    CONSTRAINT "BasicHealthUnit_pkey" PRIMARY KEY ("CNES")
);

CREATE TABLE IF NOT EXISTS public."Death"
(
    death_id integer NOT NULL,
    date date,
    "time" time without time zone,
    location_code integer,
    investigated boolean,
    basic_cause_id character varying(10) COLLATE pg_catalog."default",
    time_relative_birth integer,
    pregnancy_type integer,
    gestational_age integer,
    birth_type integer,
    CONSTRAINT "Death_pkey" PRIMARY KEY (death_id)
);

CREATE TABLE IF NOT EXISTS public."DeathCause"
(
    basic_cause_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    description character varying(500) COLLATE pg_catalog."default",
    CONSTRAINT "DeathCause_pkey" PRIMARY KEY (basic_cause_id)
);

CREATE TABLE IF NOT EXISTS public."Deceased"
(
    deceased_id integer NOT NULL,
    occupation integer,
    marital_status integer,
    age double precision,
    weight double precision,
    education_level integer,
    race_color integer,
    sex integer,
    CONSTRAINT "Deceased_pkey" PRIMARY KEY (deceased_id)
);

CREATE TABLE IF NOT EXISTS public."Mother"
(
    mother_id integer NOT NULL,
    living_children integer,
    deceased_children integer,
    education_level integer,
    age double precision,
    occupation integer,
    CONSTRAINT "Mother_pkey" PRIMARY KEY (mother_id)
);

CREATE TABLE IF NOT EXISTS public."Municipality"
(
    "IBGE_city_code" integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "GDP" real,
    "GDP_per_capita" real,
    population_estimate_2009 double precision,
    "IBGE_state_code" integer,
    CONSTRAINT "Municipality_pkey" PRIMARY KEY ("IBGE_city_code")
);

CREATE TABLE IF NOT EXISTS public."State"
(
    "IBGE_state_code" integer NOT NULL,
    name character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT "State_pkey" PRIMARY KEY ("IBGE_state_code")
);

ALTER TABLE IF EXISTS public."BasicHealthUnit"
    ADD FOREIGN KEY ("IBGE_city_code")
    REFERENCES public."Municipality" ("IBGE_city_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Death"
    ADD FOREIGN KEY (basic_cause_id)
    REFERENCES public."DeathCause" (basic_cause_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Death"
    ADD FOREIGN KEY (death_id)
    REFERENCES public."Deceased" (deceased_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Death"
    ADD FOREIGN KEY (location_code)
    REFERENCES public."Municipality" ("IBGE_city_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mother"
    ADD CONSTRAINT "Mother_mother_id_fkey" FOREIGN KEY (mother_id)
    REFERENCES public."Deceased" (deceased_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS "Mother_pkey"
    ON public."Mother"(mother_id);


ALTER TABLE IF EXISTS public."Municipality"
    ADD CONSTRAINT "Municipality_IBGE_state_code_fkey" FOREIGN KEY ("IBGE_state_code")
    REFERENCES public."State" ("IBGE_state_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;